{% set version = "23.5.0.post1" %}
{% set menuinst_version = "2.0a" %}
# g<commit hash> from https://github.com/conda/menuinst/pull/91
{% set menuinst_build_string = "*_g237e259_60" %}
{% set constructor_version = "3.4.3" %}
{% set python_version = "3.9.15" %}  # must match "skip: true" below
# pin to 5.7 because later versions make cross-compiling fail due to a problem with the struct extension
{% set pyinstaller_version = "5.7" %}

package:
  name: conda-standalone
  version: {{ version }}

source:
  - path: ./
  # Hash from https://github.com/conda/conda/pull/11882
  - url: https://github.com/conda/conda/archive/ca65f8b.tar.gz
    folder: conda_src
    patches:
      - conda_patches/0001-Rename-and-replace-entrypoint-stub-exe.patch
      - conda_patches/0002-Manipulate-PATH-directly-instead-of-_call_ing-conda.patch
      - conda_patches/0003-Return-unknown-module-in-deprecations.patch
  - url: https://github.com/jaimergp/constructor/archive/menuinst-cep.tar.gz
    folder: constructor

build:
  number: 0
  skip: true  # [py != 39]
  ignore_run_exports:
    - '*'

requirements:
  build:
    - python {{ python_version }}  # [build_platform != target_platform]
    # These are not needed technically, but we need them here so the build env
    # is solved as closely to host as possible
    - pip  # [build_platform != target_platform]
    - pyinstaller {{ pyinstaller_version }} # [build_platform != target_platform]
    - conda ={{ version }}  # [build_platform != target_platform]
    - conda-package-handling >=1.6  # [build_platform != target_platform]
    - menuinst ={{ menuinst_version }} {{ menuinst_build_string }}  # [build_platform != target_platform]
  host:
    - pyinstaller {{ pyinstaller_version }}
    - python {{ python_version }}
    - pip
    - conda ={{ version }}
    - conda-package-handling >=1.6
    - menuinst ={{ menuinst_version }} {{ menuinst_build_string }}
  run_constrained:
    - constructor >={{ constructor_version }}
test:
  commands:
    - export CONDA_SOLVER="classic"  # [unix]
    - ${PREFIX}/standalone_conda/conda.exe -V    # [unix]
    - ${PREFIX}/standalone_conda/conda.exe python -V    # [unix]
    - ${PREFIX}/standalone_conda/conda.exe create -yq -p ./env_test zlib tqdm python={{python_version}} --repodata-fn repodata.json  # [unix]
    # - ${PREFIX}/standalone_conda/conda.exe create -yq -p ./env_test_2 napari-menu --no-deps --repodata-fn repodata.json  # [unix]
    - set "CONDA_SOLVER=classic"  # [win]
    - '%PREFIX%\standalone_conda\conda.exe -V'    # [win]
    - '%PREFIX%\standalone_conda\conda.exe python -V'    # [win]
    - '%PREFIX%\standalone_conda\conda.exe create -yq -p env_test zlib tqdm python={{python_version}} --repodata-fn repodata.json'    # [win]
    # - '%PREFIX%\standalone_conda\conda.exe create -yq -p env_test_2 napari-menu --no-deps --repodata-fn repodata.json'  # [win]

about:
  home: https://github.com/AnacondaRecipes/conda-standalone-feedstock
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Entry point and dependency collection for PyInstaller-based standalone conda.

extra:
  recipe-maintainers:
    - jaimergp
