provider:
  win: github_actions
  osx: github_actions
  linux: github_actions
conda_forge_output_validation: true
channels:
  targets:
    - - napari
upload_on_branch: main
github_actions: 
  store_build_artifacts: true
