provider:
  win: github_actions
  osx: github_actions
  linux: github_actions
conda_forge_output_validation: true
channels:
  targets:
    - - napari
github:
  branch_name: main
  tooling_branch_name: main
